# ga_problem.py
import numpy as np
import random
import subprocess
import time
import uuid

from inspyred.ec              import Individual
from multiprocessing.managers import DictProxy
from openbabel                import openbabel, pybel
from pathlib                  import Path
from rdkit                    import Chem
from rdkit.Chem               import AllChem
from subprocess               import TimeoutExpired
from typing                   import Any, Dict, List, Tuple


import constants as C

from peptide_operators import get_hydrophobicity
from utils      import print_error, print_verbose, print_warning

# --- Initial Population Generation Function ---

def peptide_generator(random: random.Random, args: Dict[str, Any]) -> str:
    """
    Generates the initial peptide sequence for the population.

    Creates a random sequence of amino acids with a fixed length 
    (defined by `PEPTIDE_LENGTH` or passed via arguments).

    Parameters
    ----------
    random : `random.Random`
        The random number generator instance provided by the `inspyred` framework.
    args : `Dict[str, Any]`
        Dictionary of optional arguments. It may contain the key 
        `'peptide_length'` (`int`) to specify the sequence length.

    Returns
    -------
    `str`
        A random peptide sequence (string of one-letter amino acid codes).

    Examples
    --------
    >>> generator = peptide_generator(random_instance, {'peptide_length': 5})
    >>> print(generator)
    'ALTSV'
    """
    length: int = args.get('peptide_length', C.PEPTIDE_LENGTH)
    return "".join(random.choice(C.AMINO_ACIDS) for _ in range(length))


# --- Helper functions and preparation pipeline (RDKit) for Structure and Docking ---

def generate_pdb_rdkit(sequence: str, output_file: str | Path) -> None:
    """
    Generates an initial 3D conformation for a peptide given its sequence.

    Uses RDKit to construct the amino acid chain, add hydrogens, generate 
    3D coordinates using the ETKDGv3 algorithm, and perform a quick 
    energy minimization (MMFF94) to relax the structure.

    Parameters
    ----------
    sequence : `str`
        The peptide sequence (e.g., 'ACDEF').
    output_file : `str` or `Path`
        The file path where the generated PDB structure will be saved.

    Returns
    -------
    `None`

    Examples
    --------
    >>> generate_pdb_rdkit("WWPYWW", "candidate.pdb")
    """
    output_file = Path(output_file)

    try:
        mol = Chem.MolFromSequence(sequence)
        if mol is None:
            raise ValueError(f"RDKit fails to parse sequence: {sequence}")
        mol = Chem.AddHs(mol)
        
        # Embedding (Generating Initial Coordinates)
        # Use ETKDGv3, which is more robust for large/cyclic molecules
        params = AllChem.ETKDGv3()
        params.useRandomCoords = True
        result = AllChem.EmbedMolecule(mol, params)
        
        if result == -1:
            # Fallback if it fails
            result = AllChem.EmbedMolecule(mol, useRandomCoords = True)
        
        if result == -1:
            raise ValueError(f"Impossibile generare conformero 3D per {sequence}")
            
        # MINIMIZATION
        # Relax the structure to avoid overlapping atoms
        AllChem.MMFFOptimizeMolecule(mol)
        
        Chem.MolToPDBFile(mol, str(output_file))
    except Exception as e:
        print_error(f"RDKit generation error for {sequence}: {e}")

def prepare_ligand_openbabel(pdb_path: str | Path, pdbqt_output_path: str | Path, center: Tuple[float, float, float]) -> bool:
    """
    Converts and prepares a ligand file (PDB) into PDBQT format using OpenBabel.

    This function performs critical steps for docking:
    1. Reads the input molecular file.
    2. Translates the molecule's centroid to the target box center.
    3. Adds polar hydrogens (protonation at pH 7.4).
    4. Calculates partial charges (Gasteiger method).
    5. Writes the .pdbqt file including the torsion tree.

    Parameters
    ----------
    pdb_path : `str` or `Path`
        The path to the input ligand PDB file.
    pdbqt_output_path : `str` or `Path`
        The destination path for the prepared PDBQT file.
    center : `Tuple[float, float, float]`
        The (x, y, z) coordinates where the ligand should be centered.

    Returns
    -------
    `bool`
        True if the preparation and file writing were successful, False otherwise.

    Examples
    --------
    >>> success = prepare_ligand_openbabel("ligand.pdb", "ligand.pdbqt", (10.5, -4.0, 32.1))
    """
    pdb_path            = Path(pdb_path)
    pdbqt_output_path   = Path(pdbqt_output_path)

    try:
        # Read PDB (Generated by RDKit, so safe)
        mol = next(pybel.readfile("pdb", str(pdb_path)))
        
        # Centering in the pocket (Box Vina)
        atoms         = [atom.coords for atom in mol] 
        centroid      = np.mean(atoms, axis = 0)
        target_center = np.array([center[0], center[1], center[2]])
        move_v        = target_center - centroid
        mol.OBMol.Translate(openbabel.vector3(move_v[0], move_v[1], move_v[2]))
        
        # PDBQT writing (OpenBabel calculates Gasteiger charges automatically)
        mol.write("pdbqt", str(pdbqt_output_path), overwrite = True)
        
        return pdbqt_output_path.exists() and pdbqt_output_path.stat().st_size > 0
    except StopIteration:
        print_error(f"OpenBabel Error: Empty or invalid PDB file: {pdb_path}")
        return False
    except Exception as e:
        print_error(f"Conversion failed for {pdb_path}: {e}")
        return False
    

def run_vina_real(vina_exe_path: str | Path, pdbqt_ligand: str | Path, receptor_file: str | Path, center: Tuple[float, float, float], box_size: Tuple[int, int, int], vina_output: str | Path, cpu: int = 1, exhaustiveness: int = C.EXHAUSTIVENESS, time_left: float = float("inf"), verbose: bool = False) -> float:
    """
    Executes molecular docking by launching the AutoDock Vina process.

    Builds and runs the command line for Vina, specifying the receptor, ligand, 
    search box, and precision parameters. Captures standard output to parse 
    and extract the best binding affinity score (free energy).

    Parameters
    ----------
    vina_exe_path : `str` or `Path`
        Path to the AutoDock Vina executable.
    pdbqt_ligand : `str` or `Path`
        Path to the prepared ligand file (.pdbqt).
    receptor_file : `str` or `Path`
        Path to the prepared receptor file (.pdbqt).
    center : `Tuple[float, float, float]`
        The (x, y, z) coordinates of the search box center.
    box_size : `Tuple[float, float, float]`
        The (x, y, z) dimensions of the search box in Ångstroms.
    vina_output : `str` or `Path`
        Path where the docking poses (PDBQT) will be saved.
    cpu : `int`, optional
        Number of CPUs to use for this specific Vina run (default is 1).
    exhaustiveness : `int`, optional
        Search exhaustiveness parameter (default is 8). Higher means more accurate but slower.
    time_left : `float`, optional
        Maximum time allowed (in seconds) for the subprocess before timeout.
    verbose : `bool`, optional
        If True, prints debug information.

    Returns
    -------
    `float`
        The binding energy of the best mode (kcal/mol). 
        Returns `float('inf')` if docking fails or no modes are found.

    Examples
    --------
    >>> energy = run_vina_real("vina", "lig.pdbqt", "rec.pdbqt", (0,0,0), (20,20,20), "out.pdbqt")
    >>> print(energy)
    -9.4
    """
    vina_exe_path = Path(vina_exe_path)
    pdbqt_ligand  = Path(pdbqt_ligand)
    receptor_file = Path(receptor_file)
    vina_output   = Path(vina_output)

    if not receptor_file.exists():
        print_error(f"CRITICAL ERROR: The receptor file does not exist: {receptor_file}")
        return float('inf')
            
    cmd = [
        vina_exe_path,
        "--receptor"      , str(receptor_file),
        "--ligand"        , str(pdbqt_ligand),
        "--center_x"      , str(center[0]),
        "--center_y"      , str(center[1]),
        "--center_z"      , str(center[2]),
        "--size_x"        , str(box_size[0]),
        "--size_y"        , str(box_size[1]),
        "--size_z"        , str(box_size[2]),
        "--exhaustiveness", str(exhaustiveness),
        "--cpu"           , str(cpu),
        "--out"           , str(vina_output),
        # "--score_only" 
    ]
    
    try:
        result = subprocess.run(
            cmd,
            capture_output = True,
            text           = True,
            check          = True,
            timeout        = time_left
        )
        
        for line in result.stdout.splitlines():
            if line not in {
                '#################################################################',
                '# If you used AutoDock Vina in your work, please cite:          #',
                '#                                                               #',
                '# O. Trott, A. J. Olson,                                        #',
                '# AutoDock Vina: improving the speed and accuracy of docking    #',
                '# with a new scoring function, efficient optimization and       #',
                '# multithreading, Journal of Computational Chemistry 31 (2010)  #',
                '# 455-461                                                       #',
                '#                                                               #',
                '# DOI 10.1002/jcc.21334                                         #',
                '#                                                               #',
                '# Please see http://vina.scripps.edu for more information.      #',
                '#################################################################',
                'Reading input ... done.',
                'Setting up the scoring function ... done.',
                'Analyzing the binding site ... done.',
                'Performing search ...               ',
                '',
                '0%   10   20   30   40   50   60   70   80   90   100%',
                '|----|----|----|----|----|----|----|----|----|----|',
                '***************************************************',
                'done.',
                'Refining results ... done.',
            } and "Using random seed:" not in line and "Performing search ..." not in line:
                # print_verbose(line, to_print = verbose)
                # Search for patterns like: "   1        -8.5      0.000      0.000"
                if line.strip().startswith("1"):
                    parts = line.split()
                    if len(parts) >= 2:
                        try:
                            return float(parts[1])
                        except ValueError:
                            continue
                
                # Search for patterns like: "Affinity: -8.5"
                if "Affinity:" in line:
                    parts = line.split()
                    if len(parts) >= 2: 
                        return float(parts[1])
        return float('inf') # If parsing fails
    except subprocess.CalledProcessError as e:
        # Vina returned an error code
        print_error(f"Vina Error Output: {e.stderr}")
        return float('inf')
    except TimeoutExpired:
        print_warning(f"[TIME LIMIT] Vina interrupted for sequence '{Path(pdbqt_ligand).stem.split('_')[0]}': Global Job limit reached.")
        return float('inf')
    except Exception as e:
        print_error(f"Vina execution error (subprocess): {e}")
        return float('inf')


# --- Main Evaluation Function ---

def evaluate_peptide_binding(candidates: List[Individual], args: Dict[str, Any]) -> List[float]:
    """
    Evaluates the binding affinity (fitness) of a list of peptide candidates.

    For each peptide:
    1. Converts the sequence into a 3D structure (PDB) using RDKit.
    2. Prepares the ligand (PDBQT) using OpenBabel.
    3. Performs docking against the receptor using AutoDock Vina.
    4. Calculates fitness as: Binding Energy + (Hydrophobicity * Weight).

    Parameters
    ----------
    candidates : `List[str]`
        A list of peptide sequences to evaluate.
    args : `Dict[str, Any]`
        Dictionary containing simulation parameters (receptor path, box size, 
        mutation rates, hydrophobicity weights, etc.).

    Returns
    -------
    `List[float]`
        A list of fitness values corresponding to the candidates. 
        Lower values indicate better fitness (stronger binding/optimization).

    Examples
    --------
    >>> scores = evaluate_peptide_binding(['WWPYWW'], {'receptor_file': '...'})
    >>> print(scores)
    [-11.25]
    """
    # Reading parameters with fallback
    job_id                : str              = args.get('job_id', str(uuid.uuid4()))
    verbose               : bool             = args.get('verbose', False)
    vina_exe_path         : Path             = Path(args.get('vina_exe_path', C.VINA_EXE_PATH))
    hydrophobicity_weight : float            = args.get('hydrophobicity_weight', C.HYDROPHOBICITY_WEIGHT)
    receptor_file         : Path             = Path(args.get('receptor_file', C.RECEPTOR_FILE))
    multiprocessing_cache : DictProxy | None = args.get('multiprocessing_cache', None)
    global_deadline       : float            = args.get('global_deadline', float('inf'))
    print_lock            : Any              = args.get('print_lock', None)
    
    cx = args.get('center_x', C.CENTER_X)
    cy = args.get('center_y', C.CENTER_Y)
    cz = args.get('center_z', C.CENTER_Z)
    
    sx = args.get('size_x', C.SIZE_X)
    sy = args.get('size_y', C.SIZE_Y)
    sz = args.get('size_z', C.SIZE_Z)
        
    # Temporary JOB directory (must exist, created by main.py)
    # If for some reason it doesn't exist, use the local /tmp with fallback
    base_temp = Path(args.get('temp_dir', f"tmp/bioai_ga_{job_id}"))
    if not base_temp.exists():
        print_verbose(f"[evaluate_peptide_binding] Creating a temporary directory '{base_temp}' ...", to_print = verbose, lock = print_lock)
        base_temp.mkdir(parents = True, exist_ok = True)
        if base_temp.exists():
            print_verbose(f"[evaluate_peptide_binding] Creating a temporary directory '{base_temp}' --> Done.", to_print = verbose, lock = print_lock)
        else:
            print_error(f"[evaluate_peptide_binding] Temporary directory '{base_temp}' not created!", code = -1, lock = print_lock)

    fitnesses = []
    for candidate in candidates:
        seq = candidate.candidate if hasattr(candidate, 'candidate') else candidate

        if multiprocessing_cache is not None and seq in multiprocessing_cache:
            print_verbose(f"[evaluate_peptide_binding] Cache hit for '{seq}'. Fetching fitness from cache.", to_print = verbose, lock = print_lock)
            fitnesses.append(multiprocessing_cache[seq])
            continue

        if time.time() > global_deadline - C.SAFETY_MARGIN:
            print_warning(f"[TIME LIMIT] Preemptive skip of '{seq}'.", lock = print_lock)
            fitnesses.append(float('inf'))
            continue # DO NOT SAVE IN CACHE: will try again at the next reboot

        hydrophobicity = get_hydrophobicity(seq)
        
        # Create isolated folder for this single peptide
        peptide_dir   = base_temp / f"p_{seq}_{job_id}"

        print_verbose(f"[evaluate_peptide_binding] Creating peptide directory '{seq}' in '{peptide_dir}' ...", to_print = verbose, lock = print_lock)
        peptide_dir.mkdir(parents = True, exist_ok = True)
        if peptide_dir.exists():
            print_verbose(f"[evaluate_peptide_binding] Creating peptide directory '{seq}' in '{peptide_dir}' --> Done.", to_print = verbose, lock = print_lock)
        else:
            print_error(f"[evaluate_peptide_binding] Peptide Directory '{seq}' in '{peptide_dir}' not created!", code = -1, lock = print_lock)

        base_name  = peptide_dir / f"{seq}_{job_id}"
        pdb_file   = Path(f"{base_name}.pdb")
        pdbqt_file = Path(f"{base_name}.pdbqt")
        out_file   = Path(f"{base_name}_out.pdbqt")
        
        try:
            time_left    = global_deadline - time.time()
            if time_left <= C.SAFETY_MARGIN:
                raise TimeoutExpired(vina_exe_path, 0, f"Global time running out ({time_left}s <= 60s) before starting")
            
            # Structure Generation
            print_verbose(f"[evaluate_peptide_binding] Generation Structure of '{seq}' in '{pdb_file}' ...", to_print = verbose, lock = print_lock)
            generate_pdb_rdkit(seq, pdb_file)
            print_verbose(f"[evaluate_peptide_binding] Generation Structure of '{seq}' in '{pdb_file}' --> Done.", to_print = verbose, lock = print_lock)
            
            # Pybel -> RDKit (Centering)
            print_verbose(f"[evaluate_peptide_binding] Converting '{pdb_file}' to '{pdbqt_file}' and centering at ({cx}, {cy}, {cz}) of sequence '{seq}' ...", to_print = verbose, lock = print_lock)
            if prepare_ligand_openbabel(pdb_file, pdbqt_file, (cx, cy, cz)):
                print_verbose(f"[evaluate_peptide_binding] Autodock Vina evaluation on '{pdbqt_file}' of sequence '{seq}' ...", to_print = verbose, lock = print_lock)
                energy = run_vina_real(
                    vina_exe_path  = vina_exe_path,
                    pdbqt_ligand   = pdbqt_file,
                    receptor_file  = receptor_file,
                    center         = (cx, cy, cz),
                    box_size       = (sx, sy, sz),
                    vina_output    = out_file,
                    cpu            = 1,             # 1 CPU per processo figlio
                    exhaustiveness = args.get('exhaustiveness', C.EXHAUSTIVENESS),
                    time_left      = time_left,
                    verbose        = verbose
                )
                print_verbose(f"[evaluate_peptide_binding] Autodock Vina evaluation on '{pdbqt_file}' of sequence '{seq}' --> Done", to_print = verbose, lock = print_lock)
                
                # uses the hydrophobicity average as a penalty to narrow down the range of possible solutions
                final_fitness = energy + (hydrophobicity * hydrophobicity_weight)
                fitnesses.append(final_fitness)
                print_verbose(f"[evaluate_peptide_binding] Final fitness for sequence '{seq}': Energy = {energy} + Hydrophobicity Penalty ({hydrophobicity} * {hydrophobicity_weight}) = {final_fitness}", to_print = verbose, lock = print_lock)

                if multiprocessing_cache is not None:
                    multiprocessing_cache[seq] = final_fitness
                print_verbose(f"[evaluate_peptide_binding] Converting '{pdb_file}' to '{pdbqt_file}' and centering at ({cx}, {cy}, {cz}) of sequence '{seq}' --> Done", to_print = verbose, lock = print_lock)
            else:
                fitnesses.append(float('inf'))               # Penalty for failure to prep
                print_verbose(f"[evaluate_peptide_binding] Converting '{pdb_file}' to '{pdbqt_file}' and centering at ({cx}, {cy}, {cz}) of sequence '{seq}' --> Failed", to_print = verbose, lock = print_lock)
            
        except TimeoutExpired:
            print_warning(f"[TIME LIMIT] Evaluation interrupted due to sequence '{seq}': Global Job limit reached.", lock = print_lock)
            fitnesses.append(float('inf'))                   # Maximum timeout penalty
        
        except Exception as e:
            print_error(f"CRITICAL EVAL ERROR of \"{seq}\": {e}", lock = print_lock)
            fitnesses.append(float('inf'))                   # Maximum penalty in case of failure
            
    return fitnesses
